language: r
cache: packages
sudo: false

r:
- release
- devel

os:
- linux
- osx

r_packages:
- Rcpp
- RcppArmadillo
- ggplot2
- igraph
- mclust
- knitr
- rmarkdown
- viridis

r_build_args: "--html --no-manual"

r_check_args: "--as-cran --timings"
